### PR TITLE
pkg/mesh: optionally prioritise private addresses

### PR DESCRIPTION
**Pull request by sbaildon**
Optionally prefer a node's external IP be set to it's private IP

> If deploying a cluser to a cloud provider across regions with a shared VPC, I'd probably want my traffic to stay inside the VPC to limit any bandwidth egress charges or slower links

https://github.com/squat/kilo/issues/229#issuecomment-903252431

### CODE REVIEW

**Comment by squat** [comment]
hi @sbaildon sorry i didn't TAL at this, I didn't realize it was waiting on me because it had WIP in the title :facepalm: 
I think this is totally the right approach. Would you consider re-opening? :)

**Comment by sbaildon** [comment]
> hi @sbaildon sorry i didn't TAL at this, I didn't realize it was waiting on me because it had WIP in the title 🤦
> I think this is totally the right approach. Would you consider re-opening? :)

No problem. It fell off my todo shortlist, and no one likes stale PRs

**Comment by squat** [comment]
This looks clean to me, can we rebase and mark as non-WIP?

**Comment by sbaildon** [comment]
Given the tests pass, and you're okay with the code, I can squash before merging

**Comment by squat** [comment]
What do you think @leonnicolas?

**Review by leonnicolas — APPROVED** [review]

**Comment by squat** [comment]
🎉🎉🎉

**Pull request merged**
