### PR TITLE
pkg/iptables: reduce calls to iptables

### LINKED ISSUE #113: Reduce amount of processes spawned by Kilo
Kilo currently spawns about 50 processes on my machine per 30s (this is a small cluster). That seems to take considerable CPU resources (it spawns the most processes out of anything on my machine). Especially since it needs to take the xtables lock which causes large slowdowns due to the conflicts with kube-router.

It seems like a few things should be done to speed this up and remove the overhead:
- Allow configuring the resync period (specifically the iptables part). It seems like the reconfiguration of the iptables rules is a failsafe and could be either removed entirely or run less frequently.
- Use ipsets instead of iptables for the list of ip ranges
- Load the entire KILO-NAT chain/ipset and compare against that instead of checking each rule individually

### PR DESCRIPTION
**Pull request by squat**
Currently, every time the iptables controller syncs rules, it spawns an
an iptables process for every rule it checks. This causes two problems:
1. it creates unnecessary load on the system; and
2. it causes contention on the xtables lock file.

This commit creates a lazy cache for iptables rules and chains that
avoids spawning iptables processes. This means that each time the
iptables rules are reconciled, if no rules need to be changed then at
most one iptables process should be spawned to check all of the rules in
a chain and at most one process should be spawned to check all of the
chains in a table.

Note: the success of this reduction in calls to iptables depends on a
somewhat fragile comparison of iptables rule text. The text of any rule
must match exactly, including the order of the flags. An improvement to
come would be to implement an iptables rule parser than can be used to
check semantic equivalence betweem iptables rules.

Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

cc @leonnicolas @SerialVelocity

Fixes #113

### CODE REVIEW

**Comment by SerialVelocity** [comment]
Since you mention this is so fragile, is it worth adding an info log line with the amount of rules that needed updating? (but not output anything if nothing needs changing)

**Comment by squat** [comment]
@SerialVelocity I added the log statement to the iptables controller. PTAL :+1:

**Comment by SerialVelocity** [comment]
Did you accidentally push this to the latest tag? The reason I ask is the latest tag was updated an hour ago but the last master commit was 2 days ago.

**Comment by squat** [comment]
No I didnt :/ let me see what happened, maybe CI is misconfigured

**Comment by squat** [comment]
The 'latest' tag has exactly the same hash as the images tagged '0d0fdda619938fc1671dadff4c55597ed1795913', and in fact they were pushed at the same time, ~8 hours ago, which corresponds to midnight UTC. This is the SHA of the latest commit on master. These images were built by the CI cron job that runs every day at midnight and rebuilds the tip of master.

**Comment by squat** [comment]
ping @SerialVelocity have you have any time to rebase your fork onto this branch and test it? I removed the log lines as you suggested so we should be able to see the reduction in CPU load.

Thanks for your help!

**Comment by SerialVelocity** [comment]
Oh! I didn't realise you were waiting on me! I'll check it out now.

**Comment by SerialVelocity** [comment]
Is there a 5 second timer anywhere? Kilo seems to run the iptables commands every 5 seconds. (It's a lot less than before though!)

**Comment by squat** [comment]
Yes exactly: https://github.com/squat/kilo/blob/main/pkg/iptables/iptables.go#L226
Right now Kilo re-checks the iptables config every 5 seconds. We can probably make this a lot less aggressive, e.g. every 30 seconds. WDYT?

**Comment by SerialVelocity** [comment]
If something changes and the iptables rules need updating, does it have to wait for that 5 second loop? If not, then yeah, 30s sounds much better (if not even higher)

**Comment by squat** [comment]
If the mesh changes, then the new rules are applied immediately rather than waiting for this timer. The 5 second timeout is to quickly catch rules that were changed by another process or someone mucking around on the host. This reconciliation is "just in case" so we can probably turn it down a bit. Ok, with that in place i think we can merge this! Thanks for your input and testing @SerialVelocity !

**Comment by SerialVelocity** [comment]
I think having a short 5 second reconciliation loop is probably bad as people will wonder why they have small blips of network connectivity. Having this much higher means the issue will be noticed, debugged, and fixed.

**Pull request merged**
