### PR TITLE
enh(Dockerfile): bump alpine repos used to install dependencies

### PR DESCRIPTION
**Pull request by TPXP**
Followup for #389

### CODE REVIEW

**Comment by TPXP** [comment]
@squat Sorry I missed that, I'm afraid it will most certainly still install outdated binaries without it :(

**Review by squat — APPROVED** [review]

**Comment by squat** [comment]
Oh wow, you're totally right!

**Comment by squat** [comment]
I need to confirm, but I'm pretty sure this extra bit of config can eventually be removed. It was necessary back in the day when we were on the bleeding edge of Alpine package management and needed the most recent packages versions for the WireGuard CLI to work.

**Comment by TPXP** [comment]
I think you can indeed drop this part and rely on the default repos to install alpine packages, good idea. 👍 

I don't have the context for this addition, but if official repos work we should use them

**Pull request merged**
