### PR TITLE
pkg/k8s: update generated licenses

### PR DESCRIPTION
**Pull request by squat**
After running make, the licenses for the generated go files is updated,
resulting in a diff in the repository. This makes later invocations of
`make container` generate tags with `$ARCH-$SHA-dirty` rather than just
`$ARM-$SHA`, which causes `make manifest` to fail, as some of the
images cannot be found.

A more permanent fix would be to ensure that running `make container`
does not cause the go code to unnecessarily regenerated, but this will
at least fix CI until next year.

xref: https://github.com/squat/kilo/runs/4702120861?check_suite_focus=true#step:7:532

Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

### CODE REVIEW

**Comment by squat** [comment]
ping @leonnicolas ❤️

**Comment by squat** [comment]
Merging to unblock CI

**Comment by leonnicolas** [comment]
sorry i didn't see

**Comment by squat** [comment]
No worries @leonnicolas ❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Pull request merged**
