### PR TITLE
Bump go and container base image

### PR DESCRIPTION
**Pull request by leonnicolas**
- bump golang 1.17 -> 1.18
 - bump alpine 3.14 -> 3.15
 - revendor

 We need to use golang instead of golang:alpine because it does not
 contain git anymore. This should be fine as we are not enabling CGO,
 thus not linking against musl instead of libc.

Signed-off-by: leonnicolas <leonloechner@gmx.de>

### CODE REVIEW

**Review by squat — COMMENTED** [review]
nice @leonnicolas :) let's re-vendor and we can merge!

**Comment by leonnicolas** [comment]
it's the CI image

**Comment by squat** [comment]
ahhh :+1:

**Review by squat — APPROVED** [review]
:tada:

**Pull request merged**
